7 separate controllers add tests
NotarizedScreenshot/external-adapter pull request #39
Opened 2023-03-30 07:06 UTC by poludnev

2023-04-09 19:37 UTC, utgarda requested changes
A bit of refactoring will be in order, mostly extracting code to functions, and have a look at `package.json` and README.md please.

2023-04-09 19:37 UTC, utgarda commented on src/helpers/images.ts
> +    console.log('create img problem: ', e);
A more detailed log message could be useful.

2023-04-09 19:37 UTC, utgarda commented on src/helpers/index.ts
> +    }, null).content.itemContent;
What does this do? Does it find a single entry - if so, some kind of filter function should do better,
or else if this should collect multiple items, it should append something to acc.

2023-04-09 19:37 UTC, utgarda commented on src/helpers/index.ts
> +export const getTweetTimelineEntries = (
Let's leave timeline entries out of this version.

2023-04-09 19:37 UTC, utgarda commented on src/models/index.ts
> +            const minBitrateVariant = video_info.variants.reduce((acc, val) => {
in case you use `minBy` more than once, please define it
https://decipher.dev/30-seconds-of-typescript/docs/maxBy/

2023-04-09 19:37 UTC, utgarda commented on src/queue/index.ts
> +  console.log('uploadQueue job started');
Adding more info like job ID should result in more useful logs

2023-04-09 19:37 UTC, utgarda commented on src/queue/index.ts
> +  const client = new NFTStorage({ token: process.env.NFT_STORAGE_TOKEN! });
Is it possible to (re)initialize the client outside this loop? Not crucial, I believe, just asking

2023-04-13 07:54 UTC, poludnev commented on src/models/index.ts
> +            const minBitrateVariant = video_info.variants.reduce((acc, val) => {
I use it here once, and at the same time minBy from the sample by link is used to get a max value of a property of object-type elements, while I need to get a url by max max bitrate value: { url: string, bitrate: number}[], so will consider for the future refactoring if reused.

2023-04-13 08:17 UTC, poludnev commented on src/helpers/index.ts
> +export const getTweetTimelineEntries = (
Timeline will be filtered in the controller by tweetId

2023-04-17 16:57 UTC, pixelPepe requested changes

2023-04-17 16:57 UTC, pixelPepe commented on Dockerfile
>      && apt-get install -y nano \
remove unused nano

2023-04-17 16:57 UTC, pixelPepe commented on src/controllers/adapterResponse.ts
> +    const ts = Date.now();
better to call this variable as timeStamp

2023-04-17 16:57 UTC, pixelPepe commented on src/controllers/adapterResponse.ts
> +    const nftMmetadataCid = await updloadTweetToCAS(
rename this const to nftMetadataCid

2023-04-17 16:57 UTC, pixelPepe commented on src/controllers/getScreenShot.ts
> +//
no newline

2023-04-19 19:36 UTC, utgarda requested changes
Looks solid! Please take care of the minor issues mentioned.

2023-04-19 19:36 UTC, utgarda commented on src/helpers/index.ts
>    return `${url.split(':').join('_').split('/').join('_').split('.').join('_')}.png`;
```typescript
> "1,,,b:a/c:d.e:f///g:h".split(/[,.:\/]+/).join('_')
'1_b_a_c_d_e_f_g_h'
```

2023-04-19 19:36 UTC, utgarda commented on src/helpers/index.ts
>    return `${url.split(':').join('_').split('/').join('_').split('.').join('_')}_stamp.png`;
.

2023-04-19 19:36 UTC, utgarda commented on src/helpers/index.ts
>    return `${url.split(':').join('_').split('/').join('_').split('.').join('_')}.json`;
```typescript
.split(':').join('_').split('/').join('_').split('.').join('_')
```
is used 3 times at least, please extract to a function

2023-04-19 19:36 UTC, utgarda commented on src/controllers/adapterResponse.ts
> +      // @ts-ignore
`getTrustedHashSum`

2023-04-19 19:36 UTC, utgarda commented on src/helpers/index.ts
> +        }
Used twice, can this go to a tiny helper?

2023-04-19 19:36 UTC, utgarda commented on src/helpers/nftStorage.ts
> +  const client = new NFTStorage({ token: process.env.NFT_STORAGE_TOKEN! });
Try putting client creation outside the Bull queue item processing if it's not too much fuss.

2023-04-19 19:36 UTC, utgarda commented on src/queue/index.ts
> +  const screenshotCid = await updloadTweetToCAS(Buffer.from(screenshotImageBuffer!));
Should this be named "uploadToCAS"?

2023-04-19 19:36 UTC, utgarda commented on src/queue/index.ts
> +  const stampedScreenShotCid = await updloadTweetToCAS(Buffer.from(stampedImageBuffer!));
Consider parallel uploads in the future.

2023-04-19 19:36 UTC, utgarda commented on tests/controllers.test.ts
> +      //TODO: write tests
Yeah, write some please. Doesn't have to be huge.

2023-04-19 19:36 UTC, utgarda commented on tests/helpers.test.ts
> +    //TODO: write tests
@pixelPepe come join us here for a few lines!

2023-04-23 08:13 UTC, utgarda commented on Dockerfile
> +CMD ["sh", "-c", "redis-server --daemonize yes && npm start"]
https://github.com/NotarizedScreenshot/external-adapter/issues/47

2023-04-23 08:16 UTC, utgarda commented on config.env
>  NFT_STORAGE_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDY3Y2NmMWU0OEU4NWViNzVFQzUzRmEzODU2NzZGOEVEM0Q2OWYxOWMiLCJpc3MiOiJuZnQtc3RvcmFnZSIsImlhdCI6MTY1NzcxMDM1NDA0OSwibmFtZSI6
https://github.com/NotarizedScreenshot/external-adapter/issues/48

2023-04-23 08:23 UTC, utgarda approved these changes
Kindly take care of the test coverage

2023-04-23 08:23 UTC, utgarda commented on src/helpers/handlers.ts
> +  // const mediaUrls = Array.from(new Set([...tweetsDataUrlsToUpload]));
Is this for something specific later?

2023-04-23 08:23 UTC, utgarda commented on tests/controllers.test.ts
> +      //TODO: write tests
:)

2023-04-23 08:23 UTC, utgarda commented on tests/helpers.test.ts
> +    //TODO: write tests
.

2023-04-26 10:50 UTC, merged